site:
    resource: "@SiteBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

admin_user_security:
    resource: "@AdminBundle/Resources/config/routing/security.yml"
    prefix: /admin/profile

admin_user_profile:
    resource: "@AdminBundle/Resources/config/routing/profile.yml"
    prefix: /admin/profile

admin_user_change_password:
    resource: "@AdminBundle/Resources/config/routing/change_password.yml"
    prefix: /admin/profile